# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qtdesigner/ContactEditor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ContactEditor(object):
    def setupUi(self, ContactEditor):
        ContactEditor.setObjectName("ContactEditor")
        ContactEditor.resize(370, 540)
        ContactEditor.setMinimumSize(QtCore.QSize(370, 540))
        ContactEditor.setMaximumSize(QtCore.QSize(370, 540))
        self.first_name = QtWidgets.QLineEdit(ContactEditor)
        self.first_name.setGeometry(QtCore.QRect(140, 90, 181, 22))
        self.first_name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.first_name.setText("")
        self.first_name.setReadOnly(False)
        self.first_name.setObjectName("first_name")
        self.email = QtWidgets.QLineEdit(ContactEditor)
        self.email.setGeometry(QtCore.QRect(140, 210, 181, 22))
        self.email.setText("")
        self.email.setObjectName("email")
        self.label_1 = QtWidgets.QLabel(ContactEditor)
        self.label_1.setGeometry(QtCore.QRect(50, 90, 81, 21))
        self.label_1.setObjectName("label_1")
        self.url = QtWidgets.QLineEdit(ContactEditor)
        self.url.setGeometry(QtCore.QRect(140, 250, 181, 22))
        self.url.setText("")
        self.url.setObjectName("url")
        self.notes = QtWidgets.QTextEdit(ContactEditor)
        self.notes.setGeometry(QtCore.QRect(140, 290, 181, 81))
        self.notes.setObjectName("notes")
        self.label_6 = QtWidgets.QLabel(ContactEditor)
        self.label_6.setGeometry(QtCore.QRect(50, 290, 81, 21))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(ContactEditor)
        self.label_5.setGeometry(QtCore.QRect(50, 250, 81, 21))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(ContactEditor)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 81, 21))
        self.label_2.setObjectName("label_2")
        self.telephone = QtWidgets.QLineEdit(ContactEditor)
        self.telephone.setGeometry(QtCore.QRect(140, 170, 181, 22))
        self.telephone.setText("")
        self.telephone.setObjectName("telephone")
        self.scrollArea = QtWidgets.QScrollArea(ContactEditor)
        self.scrollArea.setGeometry(QtCore.QRect(40, 390, 291, 91))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 291, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.last_name = QtWidgets.QLineEdit(ContactEditor)
        self.last_name.setGeometry(QtCore.QRect(140, 130, 181, 22))
        self.last_name.setObjectName("last_name")
        self.label_3 = QtWidgets.QLabel(ContactEditor)
        self.label_3.setGeometry(QtCore.QRect(50, 170, 81, 21))
        self.label_3.setObjectName("label_3")
        self.delete_button = QtWidgets.QPushButton(ContactEditor)
        self.delete_button.setEnabled(True)
        self.delete_button.setGeometry(QtCore.QRect(50, 485, 270, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_button.sizePolicy().hasHeightForWidth())
        self.delete_button.setSizePolicy(sizePolicy)
        self.delete_button.setMinimumSize(QtCore.QSize(200, 0))
        self.delete_button.setMaximumSize(QtCore.QSize(281, 500))
        self.delete_button.setObjectName("delete_button")
        self.label_7 = QtWidgets.QLabel(ContactEditor)
        self.label_7.setGeometry(QtCore.QRect(50, 370, 60, 16))
        self.label_7.setObjectName("label_7")
        self.contactName = QtWidgets.QLabel(ContactEditor)
        self.contactName.setGeometry(QtCore.QRect(55, 45, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.contactName.setFont(font)
        self.contactName.setText("")
        self.contactName.setAlignment(QtCore.Qt.AlignCenter)
        self.contactName.setObjectName("contactName")
        self.label_4 = QtWidgets.QLabel(ContactEditor)
        self.label_4.setGeometry(QtCore.QRect(50, 210, 81, 21))
        self.label_4.setObjectName("label_4")
        self.save_button = QtWidgets.QPushButton(ContactEditor)
        self.save_button.setGeometry(QtCore.QRect(250, 10, 71, 32))
        self.save_button.setObjectName("save_button")

        self.retranslateUi(ContactEditor)
        QtCore.QMetaObject.connectSlotsByName(ContactEditor)

    def retranslateUi(self, ContactEditor):
        _translate = QtCore.QCoreApplication.translate
        ContactEditor.setWindowTitle(_translate("ContactEditor", "Form"))
        self.first_name.setPlaceholderText(_translate("ContactEditor", "First Name"))
        self.email.setPlaceholderText(_translate("ContactEditor", "example@email.com"))
        self.label_1.setText(_translate("ContactEditor", "First Name:"))
        self.url.setPlaceholderText(_translate("ContactEditor", "www.example.com"))
        self.notes.setPlaceholderText(_translate("ContactEditor", "Notes..."))
        self.label_6.setText(_translate("ContactEditor", "Notes:"))
        self.label_5.setText(_translate("ContactEditor", "Url:"))
        self.label_2.setText(_translate("ContactEditor", "Last Name:"))
        self.telephone.setPlaceholderText(_translate("ContactEditor", "Telephone"))
        self.last_name.setPlaceholderText(_translate("ContactEditor", "Last Name"))
        self.label_3.setText(_translate("ContactEditor", "Telephone:"))
        self.delete_button.setText(_translate("ContactEditor", "Delete Contact"))
        self.label_7.setText(_translate("ContactEditor", "Tags:"))
        self.label_4.setText(_translate("ContactEditor", "E-mail:"))
        self.save_button.setText(_translate("ContactEditor", "Save"))

