# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qtdesigner/ContactList.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ContactList(object):
    def setupUi(self, ContactList):
        ContactList.setObjectName("ContactList")
        ContactList.resize(370, 540)
        ContactList.setMinimumSize(QtCore.QSize(370, 540))
        ContactList.setMaximumSize(QtCore.QSize(370, 540))
        self.title = QtWidgets.QLabel(ContactList)
        self.title.setGeometry(QtCore.QRect(90, 15, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayoutWidget = QtWidgets.QWidget(ContactList)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 331, 96))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchbar = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.searchbar.setEnabled(True)
        self.searchbar.setMaximumSize(QtCore.QSize(99996, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.searchbar.setFont(font)
        self.searchbar.setObjectName("searchbar")
        self.verticalLayout.addWidget(self.searchbar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayoutFilter_2 = QtWidgets.QVBoxLayout()
        self.verticalLayoutFilter_2.setContentsMargins(0, 4, -1, -1)
        self.verticalLayoutFilter_2.setObjectName("verticalLayoutFilter_2")
        self.filterby_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.filterby_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.filterby_2.setObjectName("filterby_2")
        self.verticalLayoutFilter_2.addWidget(self.filterby_2)
        self.orderby = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.orderby.setObjectName("orderby")
        self.verticalLayoutFilter_2.addWidget(self.orderby)
        self.horizontalLayout.addLayout(self.verticalLayoutFilter_2)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayoutFilter = QtWidgets.QVBoxLayout()
        self.verticalLayoutFilter.setContentsMargins(0, 4, -1, -1)
        self.verticalLayoutFilter.setObjectName("verticalLayoutFilter")
        self.filterby = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.filterby.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.filterby.setObjectName("filterby")
        self.verticalLayoutFilter.addWidget(self.filterby)
        self.scroll_tag = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.scroll_tag.setObjectName("scroll_tag")
        self.verticalLayoutFilter.addWidget(self.scroll_tag)
        self.horizontalLayout.addLayout(self.verticalLayoutFilter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tag_button = QtWidgets.QPushButton(ContactList)
        self.tag_button.setGeometry(QtCore.QRect(10, 480, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tag_button.setFont(font)
        self.tag_button.setObjectName("tag_button")
        self.add_button = QtWidgets.QPushButton(ContactList)
        self.add_button.setGeometry(QtCore.QRect(310, 10, 41, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button.sizePolicy().hasHeightForWidth())
        self.add_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(40)
        self.add_button.setFont(font)
        self.add_button.setAutoFillBackground(False)
        self.add_button.setText("")
        icon = QtGui.QIcon.fromTheme("+")
        self.add_button.setIcon(icon)
        self.add_button.setAutoRepeatDelay(300)
        self.add_button.setObjectName("add_button")
        self.scrollArea = QtWidgets.QScrollArea(ContactList)
        self.scrollArea.setGeometry(QtCore.QRect(10, 165, 351, 305))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.scrollArea.setFont(font)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 351, 305))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777210, 16777215))
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonListLayout = QtWidgets.QVBoxLayout()
        self.buttonListLayout.setContentsMargins(-1, -1, 0, 0)
        self.buttonListLayout.setObjectName("buttonListLayout")
        self.verticalLayout_2.addLayout(self.buttonListLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.line = QtWidgets.QFrame(ContactList)
        self.line.setGeometry(QtCore.QRect(10, 155, 351, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(ContactList)
        self.line_2.setGeometry(QtCore.QRect(10, 470, 351, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.scrollArea.raise_()
        self.title.raise_()
        self.verticalLayoutWidget.raise_()
        self.add_button.raise_()
        self.tag_button.raise_()
        self.line.raise_()
        self.line_2.raise_()

        self.retranslateUi(ContactList)
        QtCore.QMetaObject.connectSlotsByName(ContactList)

    def retranslateUi(self, ContactList):
        _translate = QtCore.QCoreApplication.translate
        ContactList.setWindowTitle(_translate("ContactList", "Form"))
        self.title.setText(_translate("ContactList", "Contacts"))
        self.searchbar.setPlaceholderText(_translate("ContactList", "Search..."))
        self.filterby_2.setText(_translate("ContactList", "Order by:"))
        self.filterby.setText(_translate("ContactList", "Filter by:"))
        self.tag_button.setText(_translate("ContactList", "Tags"))

