# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qtdesigner/ContactAdder.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ContactAdder(object):
    def setupUi(self, ContactAdder):
        ContactAdder.setObjectName("ContactAdder")
        ContactAdder.resize(370, 540)
        ContactAdder.setMinimumSize(QtCore.QSize(370, 540))
        ContactAdder.setMaximumSize(QtCore.QSize(370, 540))
        self.label_5 = QtWidgets.QLabel(ContactAdder)
        self.label_5.setGeometry(QtCore.QRect(50, 250, 81, 21))
        self.label_5.setObjectName("label_5")
        self.last_name = QtWidgets.QLineEdit(ContactAdder)
        self.last_name.setGeometry(QtCore.QRect(140, 130, 181, 22))
        self.last_name.setObjectName("last_name")
        self.notes = QtWidgets.QTextEdit(ContactAdder)
        self.notes.setGeometry(QtCore.QRect(140, 290, 181, 81))
        self.notes.setObjectName("notes")
        self.label_1 = QtWidgets.QLabel(ContactAdder)
        self.label_1.setGeometry(QtCore.QRect(50, 90, 81, 21))
        self.label_1.setObjectName("label_1")
        self.save_button = QtWidgets.QPushButton(ContactAdder)
        self.save_button.setEnabled(False)
        self.save_button.setGeometry(QtCore.QRect(250, 10, 71, 32))
        self.save_button.setObjectName("save_button")
        self.label_2 = QtWidgets.QLabel(ContactAdder)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(ContactAdder)
        self.label_6.setGeometry(QtCore.QRect(50, 290, 81, 21))
        self.label_6.setObjectName("label_6")
        self.newContact = QtWidgets.QLabel(ContactAdder)
        self.newContact.setGeometry(QtCore.QRect(105, 45, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.newContact.setFont(font)
        self.newContact.setAlignment(QtCore.Qt.AlignCenter)
        self.newContact.setObjectName("newContact")
        self.first_name = QtWidgets.QLineEdit(ContactAdder)
        self.first_name.setGeometry(QtCore.QRect(140, 90, 181, 22))
        self.first_name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.first_name.setText("")
        self.first_name.setReadOnly(False)
        self.first_name.setObjectName("first_name")
        self.back_button = QtWidgets.QPushButton(ContactAdder)
        self.back_button.setGeometry(QtCore.QRect(50, 10, 71, 32))
        self.back_button.setObjectName("back_button")
        self.telephone = QtWidgets.QLineEdit(ContactAdder)
        self.telephone.setGeometry(QtCore.QRect(140, 170, 181, 22))
        self.telephone.setText("")
        self.telephone.setObjectName("telephone")
        self.label_3 = QtWidgets.QLabel(ContactAdder)
        self.label_3.setGeometry(QtCore.QRect(50, 170, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(ContactAdder)
        self.label_7.setGeometry(QtCore.QRect(50, 370, 60, 16))
        self.label_7.setObjectName("label_7")
        self.url = QtWidgets.QLineEdit(ContactAdder)
        self.url.setGeometry(QtCore.QRect(140, 250, 181, 22))
        self.url.setText("")
        self.url.setObjectName("url")
        self.email = QtWidgets.QLineEdit(ContactAdder)
        self.email.setGeometry(QtCore.QRect(140, 210, 181, 22))
        self.email.setText("")
        self.email.setObjectName("email")
        self.scrollArea = QtWidgets.QScrollArea(ContactAdder)
        self.scrollArea.setGeometry(QtCore.QRect(40, 395, 291, 101))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 291, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_4 = QtWidgets.QLabel(ContactAdder)
        self.label_4.setGeometry(QtCore.QRect(50, 210, 81, 21))
        self.label_4.setObjectName("label_4")
        self.label_5.raise_()
        self.last_name.raise_()
        self.notes.raise_()
        self.label_1.raise_()
        self.save_button.raise_()
        self.label_2.raise_()
        self.label_6.raise_()
        self.newContact.raise_()
        self.first_name.raise_()
        self.back_button.raise_()
        self.telephone.raise_()
        self.label_3.raise_()
        self.url.raise_()
        self.email.raise_()
        self.scrollArea.raise_()
        self.label_4.raise_()
        self.label_7.raise_()

        self.retranslateUi(ContactAdder)
        QtCore.QMetaObject.connectSlotsByName(ContactAdder)

    def retranslateUi(self, ContactAdder):
        _translate = QtCore.QCoreApplication.translate
        ContactAdder.setWindowTitle(_translate("ContactAdder", "Form"))
        self.label_5.setText(_translate("ContactAdder", "Url:"))
        self.last_name.setPlaceholderText(_translate("ContactAdder", "Last Name"))
        self.notes.setPlaceholderText(_translate("ContactAdder", "Notes..."))
        self.label_1.setText(_translate("ContactAdder", "First Name:"))
        self.save_button.setText(_translate("ContactAdder", "Save"))
        self.label_2.setText(_translate("ContactAdder", "Last Name:"))
        self.label_6.setText(_translate("ContactAdder", "Notes:"))
        self.newContact.setText(_translate("ContactAdder", "New Contact"))
        self.first_name.setPlaceholderText(_translate("ContactAdder", "First Name"))
        self.back_button.setText(_translate("ContactAdder", "Back"))
        self.telephone.setPlaceholderText(_translate("ContactAdder", "Telephone"))
        self.label_3.setText(_translate("ContactAdder", "Telephone:"))
        self.label_7.setText(_translate("ContactAdder", "Tags:"))
        self.url.setPlaceholderText(_translate("ContactAdder", "www.example.com"))
        self.email.setPlaceholderText(_translate("ContactAdder", "example@email.com"))
        self.label_4.setText(_translate("ContactAdder", "E-mail:"))

